### ISSUE TITLE
con't able to start 

### ISSUE THREAD

**Issue by ganeshbonangi** [rvagg/learnyounode#148]
D:\javascripting>node program.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\javascripting\program.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by martinheidegger** [comment]
Its a javascripting (not learnyounode) issue and it seems to be solved or @ganeshbonangi isn't answering for another reason. Anyways: I hope its okay to close this.
