### ISSUE TITLE
Juggling Async - Type Error: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by mysticuno** [rvagg/learnyounode#170]
I got the following error when submitting both my own answer and the solution

TypeError: Cannot read property 'protocol' of undefined
    at Object.exports.request (http.js:1844:14)
    at Object.exports.get (http.js:1852:21)
    at httpGet (C:\Users\Carlos Henriquez\Desktop\MIT\IAP 2015\6.148 - Web Devel
opment Competition\learnyounode\jugglingasync.js:49:8)
    at Object.<anonymous> (C:\Users\Carlos Henriquez\Desktop\MIT\IAP 2015\6.148
- Web Development Competition\learnyounode\jugglingasync.js:64:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by julianduque** [comment]
@mysticuno can you provide the solution code to take a look?

**Comment by mysticuno** [comment]
@julianduque So, I'm not entirely sure what happened, but I tried running the solution provided at https://github.com/rvagg/learnyounode/blob/master/exercises/juggling_async/solution/solution.js and it worked. I also tried running my own solution and it also works now. I have learnyounode 1.0.7 and node 0.10.35. I don't remember changing anything, but it works now.

**Comment by julianduque** [comment]
@mysticuno it seems like a failes http request, maybe a network connection, if you keep experiencing this let us know :)
