### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by jasminmayfield** [rvagg/learnyounode#177]
I'm receiving this error, any suggestions on how I can get around this?
It pops when I try to select an exercise.

```
────────────────────────────────────
 MY FIRST I/O!
 Exercise 3 of 13

Error: EACCES, permission denied '/Users/jasmin.mayfield/.config/learnyounode/current.json'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.writeFileSync (fs.js:977:15)
    at Workshopper.updateData (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:414:6)
    at Workshopper.onselect (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:522:8)
    at EventEmitter.emit (events.js:95:17)
    at process._tickCallback (node.js:419:13)
```

**Comment by martinheidegger** [comment]
@jasminmayfield can you delete your ~/.config/learnyounode folder and see if it works then?

**Comment by ralphtheninja** [comment]
@jasminmayfield Have you installed `learnyounode` with sudo?
