### ISSUE TITLE
Object is not a function in Make it Modular

### ISSUE THREAD

**Issue by danconcru** [rvagg/learnyounode#204]
Hi, I have copied the same code to the do the "Make it modular" exercise, but It doesn't work.

When I executed learnyounode run solution.js, I get this error:

filter(process.argv[2], process.argv[3], function(err, data){
^
TypeError: object is not a function
    at Object.<anonymous> (C:\Users\Boycor\learnyounode\solution.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

I dont know what's the problem.

Sorry for my English...

Thanks!!

**Comment by rvagg** [comment]
@danconcru you're going to have to paste in some code for us to look at. My guess is that you have something like:

```js
var filter = require('./filter.js')

filter(process.argv[2], process.argv[3], function(err, data){
...
```

but your "filter.js" file does something like this:

```js
module.exports.filter = function (...
```

What you actually want to do is _overwrite_ `exports` with the function rather than adding a property to it, because what you end up with otherwise is simply an object with a function property with the name `'filter'` (or whatever you use).

So, if you are doing `module.exports.filter = function ...` then you'd have to use this in your solution.js:

```js
var filter = require('./filter.js')

filter.filter(process.argv[2], process.argv[3], function(err, data){
```

But that won't do in this case because it's specifically wanting you to export a function, not a leave `exports` as an object that has a function attached to it. So you need to: `module.exports = function () ...`

**Comment by danconcru** [comment]
@rvagg this is my code:

solution_filter.js:

<pre>
var fs = require('fs')
var path = require('path')

module.exports = function (dir, filterStr, callback) {

  fs.readdir(dir, function (err, list) {
    if (err)
      return callback(err)

    list = list.filter(function (file) {
      return path.extname(file) === '.' + filterStr
    })

    callback(null, list)
  })
}

</pre>

solution.js:

<pre>
var filterFn = require('./solution_filter.js')
var dir = process.argv[2]
var filterStr = process.argv[3]

filterFn(dir, filterStr, function (err, list) {
  if (err)
    return console.error('There was an error:', err)

  list.forEach(function (file) {
    console.log(file)
  })
})
</pre>
