### ISSUE TITLE
Impossible to run/verify Exercise 7

### ISSUE THREAD

**Issue by dbonillaf** [rvagg/learnyounode#211]
Hi,

I'm using learnyounode 2.3.3 with node 0.10.36 and npm 1.4.28 on my Mac (Yosemite 10.10.1) and I think that **I have found a bug, running exercise 7**.

I have written this code:

```javascript
var http = require("http");

var url = process.argv[2];

//console.log(url);

function showHTML(response){
  response.setEncoding("utf8");
  response.on("data", function(data){
  console.log(data);});
  response.on("error", function(error){
  console.log(error);});
}

http.get(url, showHTML);
```
When I run it out of learnyounode (e.g. "node prueba7 http://www.otogami.com") it runs smoothly and I get the HTML source on my terminal, but when I do the same thing through learyounode I get:

```
/usr/local/lib/node_modules/learnyounode/exercises/http_client/exercise.js:52
  this.server.close(callback)
              ^
TypeError: Cannot call method 'close' of undefined
    at Exercise.module.exports (/usr/local/lib/node_modules/learnyounode/exercises/http_client/exercise.js:52:15)
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:260:17)
    at Exercise.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:266:5)
    at Workshopper.end (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:197:12)
    at Workshopper.done (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:329:19)
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:149:14)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:136:16
    at Exercise.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:10:14)
    at Object.oncomplete (fs.js:108:15)
```

I guess there's a problem with the learnyounode/exercises/http_client/exercise.js file but my knowledge of node is not enough good to discover how to fix it :|

**Comment by martinheidegger** [comment]
@dbonillaf So here is my problem: It works for me :tongue: Which means that it might have a problem with your computer. In the file : /usr/local/lib/node_modules/learnyounode/exercises/http_client/exercise.js

can you add `console.log` statements (with different output) at line 25, 35, 38 and 51?

**Comment by dbonillaf** [comment]
Done. Obviously *exercise.addSetup* is not executing because I only see the "51" trace...

```javascript
// set up the data file to be passed to the submission
exercise.addSetup(function (mode, callback) {
  // mode == 'run' || 'verify'
console.log("25");
  this.server = http.createServer(function (req, res) {
    // use setTimeout to slow down the output to test timing
    ;(function next (i) {
      if (i == words.length)
        return res.end()
      res.write(words[i].trim())
      setTimeout(next.bind(null, i + 1), 25)
    }(0))
  })
  console.log("35");
  this.server.listen(0, function () {
    var url = 'http://localhost:' + String(this.server.address().port)
    console.log("38");
    // give the url as the first cmdline arg to the child processes
    this.submissionArgs = [ url ]
    this.solutionArgs   = [ url ]

    callback()
  }.bind(this))
})
```

**Comment by martinheidegger** [comment]
@dbonillaf wow, super-weird.

Can you try this:

in `/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js`

replace line 328:
```JavaScript
    if (mode == 'run' || err)
      return this.end(mode, true, exercise, errback) // clean up
```

with

```
    if (mode == 'run' || err) {
      console.log("I see")
      console.log(err)
      return this.end(mode, true, exercise, errback) // clean up
    }
```

**Comment by dbonillaf** [comment]
MEGA-weird.

I have fixed it without changing a line of code: I just changed the default language of the Operating System from Spanish to English and same code now works... O___o

**Comment by martinheidegger** [comment]
@dbonillaf Can you change it back and see if it happens again?

**Comment by dbonillaf** [comment]
Nope. I change again but I cannot reproduce the error :S
