### ISSUE TITLE
Problem with  HTTP JSON API SERVER

### ISSUE THREAD

**Issue by YetiOr** [rvagg/learnyounode#221]
If I take official answer and remove everything except this:
```javascript
    var http = require('http')
    var url = require('url')
    
    var server = http.createServer(function (req, res) {
        res.writeHead(404)
        res.end()
    })  
    server.listen(Number(process.argv[2]))
```

Then while runnnig this assignment I will get error:
```
$ learnyounode run officialHTTPAPIServer.js 

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at normalizeJSON (/Users/yeti-or/Learning/node/learnNode/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:58:30)
    at BufferList._callback (/Users/yeti-or/Learning/node/learnNode/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:80:22)
    at BufferList.end (/Users/yeti-or/Learning/node/learnNode/node_modules/learnyounode/node_modules/bl/bl.js:75:10)
    at Stream.onend (stream.js:79:10)
    at Stream.emit (events.js:117:20)
    at drain (/Users/yeti-or/Learning/node/learnNode/node_modules/learnyounode/node_modules/hyperquest/node_modules/through/index.js:33:23)
    at Stream.stream.queue.stream.push (/Users/yeti-or/Learning/node/learnNode/node_modules/learnyounode/node_modules/hyperquest/node_modules/through/index.js:41:5)
    at IncomingMessage.<anonymous> (/Users/yeti-or/Learning/node/learnNode/node_modules/learnyounode/node_modules/hyperquest/index.js:60:48)
    at IncomingMessage.emit (events.js:117:20)
```

It could be fixed in answer for example: 
```javascript
      } else {
        res.writeHead(404)
        res.end('{}')
      }
```
But i suppose that it need to be fixed in program by it self.
What do you think?

**Comment by rvagg** [comment]
Yes, this should be a check in exercise.js, not so good that it'd unguarded!
