### ISSUE TITLE
Error: Cannot switch to old mode now. When try to run learnyounode

### ISSUE THREAD

**Issue by gsambrotta** [rvagg/learnyounode#270]
Hi. I just install learnyounode workshop with command:

npm install -g learnyounode

but as soon as I run learnyounode i got this error:

```MBP-di-giorgia:buzzfeed anaketa$ learnyounode

_stream_readable.js:748
throw new Error('Cannot switch to old mode now.');
^
Error: Cannot switch to old mode now.
at emitDataEvents (_stream_readable.js:748:11)
at ReadStream.Readable.resume (_stream_readable.js:733:3)
at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/menu.js:90:17)
at showMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/exerciseMenu.js:29:10)
at Workshopper.printMenu (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:355:14)
at new Workshopper (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:180:8)
at Workshopper (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper/workshopper.js:22:12)
at Object. (/usr/local/lib/node_modules/learnyounode/learnyounode.js:11:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)```

Seems this bug happen just on node version  < 0.12

**Comment by martinheidegger** [comment]
Fixing it as we speak.

**Comment by gsambrotta** [comment]
:D awesome!

**Comment by finnp** [comment]
:balloon:

**Comment by martinheidegger** [comment]
waiting on publishing of @rvagg

**Comment by Monitob** [comment]
same probleme here :(

**Comment by betasve** [comment]
I've had the same problem but as it states in the bug report itself, it happens only for versions below 0.12. So I've updated my node.js to 0.12.2 (latest stable) and everything is ok now.

**Comment by eagleats89** [comment]
I can confirm what betasve said. Same issue, node just needed an upgrade. This link helped:

http://davidwalsh.name/upgrade-nodejs
