### ISSUE TITLE
Make it modular, strange error on path.extname

### ISSUE THREAD

**Issue by Laokoont** [rvagg/learnyounode#279]
I get this error
```terminal
/Users/nachasic/Desktop/module.js:15
			if(path.extname(file) == filter) {
			        ^
TypeError: undefined is not a function
    at /Users/nachasic/Desktop/module.js:15:12
    at Array.forEach (native)
    at /Users/nachasic/Desktop/module.js:14:9
    at FSReqWrap.oncomplete (fs.js:95:15)
```

My code at main file is: 
```javascript
var module = require('./module.js');

module(process.argv[2], process.argv[3], function(err, list) {
	if(err) {
		return console.log(error);
	}
	list.forEach(function (item) { console.log(item) })
});
```
My module.js is:
```javascript
var fs = require('fs');
var path = require('path');

module.exports = function(path, filter, callback) {
	filter = '.' + filter;
	fs.readdir(path, function (err, files) {
		
		if(err) 
			return callback(err);

		var arr = [];

		files.forEach(function (file) {
			if(path.extname(file) == filter) {
				arr.push(file);
			}
		});
		return callback(null, arr);
	});
}
```
I've found a solution on the web for this challenge, it appears quite similar to my code and I still don't get what am I doing wrong.

**Comment by spottuit** [comment]
```javascript
module.exports = function(dir, filter, callback) {
    filter = '.' + filter;
    fs.readdir(dir, function (err, files) {
```

I replaced path from the module.exports function with dir and it seems to work now. You had two variables with the same name.

**Comment by Laokoont** [comment]
OMG i've been degging the thing for a good dosen of hours, must have gone blind. Thank you

**Comment by iamShekharGH** [comment]
it is a typo error,
here 

> module.exports = function(path, filter, callback) {

change the name 'path' to sumthing else, when you type path.extname it searches for it in this path and not the path module.
